"""otp_type

Revision ID: 0c7e0a5db17b
Revises: 95ee546960be
Create Date: 2026-05-03 19:11:35.031559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c7e0a5db17b'
down_revision: Union[str, Sequence[str], None] = '95ee546960be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    otp_type = postgresql.ENUM('register', name='otptype')
    otp_type.create(op.get_bind())
    op.add_column('otpcode', sa.Column('otp_type', sa.Enum('register', name='otptype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otpcode', 'otp_type')
    otp_type = postgresql.ENUM('register', name='otptype')
    otp_type.drop(op.get_bind())
    # ### end Alembic commands ###
